### PR TITLE
Fix FloatingActionButton background

### LINKED ISSUE #258: FloatingActionButton broken in 5.11.0
background is not anchored to center

### PR DESCRIPTION
**Pull request by luntik2012**
Fix #258 
Sorry for readding FloatingTextField. Fixed loop in ```onPlaceholderTextChanged```

### CODE REVIEW

**Comment by plfiorini** [comment]
Can you please take `FloatingTextField` out of this PR so we can swiftly fix FAB and then work on the text field separately taking the time it needs.

**Comment by luntik2012** [comment]
like this?

**Comment by plfiorini** [comment]
Yes I will squash all commits into one and then merge to fix the history.
You should work on different branches though, when this PR is merged your `develop` branch will not be aligned anymore (it can be fixed destroying and recreating it from `origin`). If you did create a new feature branch instead, you could just checkout the new `develop` and destroy the feature branch.

**Comment by luntik2012** [comment]
ok, I can remove fork repo and fork again

**Comment by luntik2012** [comment]
Will you merge it on 1.1.0 and not earlier? If so, I'll really make a new branch

**Comment by plfiorini** [comment]
@luntik2012 I can make an hot fix release for Fluid 1.0 tomorrow

**Comment by luntik2012** [comment]
... I've just undestood what had you mean about branching) I'm still learning git. Next time will create my own branches, it will be more adequate :) Thank you for hint

**Pull request merged**
