### PR TITLE
Date and Time Picker

### PR DESCRIPTION
**Pull request by lukasoberhoeller**
Created a DatePicker and a TimePicker component in material style

### CODE REVIEW

**Comment by oKcerG** [comment]
Thanks for your work, the code looks clean after a quick glance.
Do you have screens?
On what guidelines/other implementations did you base your work on?

**Comment by lukasoberhoeller** [comment]
I based my work on the material design guidelines (https://material.io/guidelines/components/pickers.html#) and the code on the lirios qml coding conventions (https://github.com/lirios/lirios/wiki/QML-Coding-Conventions).
Where it was possible i used the controls from Fluid. For the datepicker i used the CalendarModel, DayOfWeekRow, WeekNumberColumn and MonthGrid from Qt.labs.calendar 1.0

datepickerportrait
datepicker
yearpicker
timepicker
timepickerlandscape

**Comment by rmallah** [comment]
Cool and outstanding. This was very much needed.

**Comment by rmallah** [comment]
Thanks for the work.

**Comment by plfiorini** [comment]
Looks very nice and more complete than my work in progress in the branch `feature/picker`.
I will take a look at the code and test it ASAP.

**Comment by plfiorini** [comment]
Merged! Thanks!

**Pull request closed without merging**
